# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywKOcANsrWKOjQTxZnwXLB6eXPWd5tD1
"""

import pandas as pd
import streamlit as st
import plotly.express as px

# Load CSV file
df = pd.read_csv("all_flights.csv")

# Clean and process
df['departureTime'] = pd.to_datetime(df['departureTime'], errors='coerce')
df['price'] = pd.to_numeric(df['price'], errors='coerce')
df['durationMinutes'] = pd.to_numeric(df['durationTime'], errors='coerce')
df['carbonEmissionsThisFlight'] = pd.to_numeric(df.get('carbonEmissionsThisFlight'), errors='coerce')

# Drop missing
df = df.dropna(subset=['airline', 'departureTime', 'price', 'durationMinutes'])

# Create derived column: price per minute
df['pricePerMinute'] = df['price'] / df['durationMinutes']

# Sidebar filters
st.sidebar.header("Filters")
selected_airline = st.sidebar.selectbox("Select an airline", df['airline'].dropna().unique())

# Filtered DataFrame
filtered = df[df['airline'] == selected_airline]

# Dashboard Title
st.title("Flight Data Dashboard")
st.markdown(f"Showing results for **{selected_airline}**")

# Price over time
st.subheader("Price Over Time")
fig = px.bar(filtered, x='departureTime', y='price', hover_data=['flightNumber'])
st.plotly_chart(fig)

# Carbon emissions vs price
st.subheader("Carbon Emissions vs Price")
fig = px.scatter(filtered, x='carbonEmissionsThisFlight', y='price', hover_data=['departureTime'])
st.plotly_chart(fig)

# Price per minute
st.subheader("Price Per Minute")
fig = px.line(filtered.sort_values('departureTime'), x='departureTime', y='pricePerMinute')
st.plotly_chart(fig)

# Histogram of Prices
st.subheader("Histogram: Prices")
fig = px.histogram(filtered, x='price')
st.plotly_chart(fig)

# Histogram of Duration
st.subheader("Histogram: Duration")
fig = px.histogram(filtered, x='durationMinutes')
st.plotly_chart(fig)

# Show raw data
st.subheader("Raw Data")
st.dataframe(filtered)